apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontent-deploy
  labels:
    app: udagram-frontent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontent-app
  template:
    metadata:
      name: udagram-frontent-pod
      labels:
        app: udagram-frontent-app # Pod label
    spec:
      containers:
      - name: udagram-frontent
        image: docker.io/suneetsinghrana/udagram-frontent:latest
        ports:
        - containerPort: 80